# Generated by Django 3.2.6 on 2021-09-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('pokemon_id', models.TextField()),
                ('pokemon_name', models.TextField()),
                ('pokemon_game', models.TextField()),
                ('count', models.DecimalField(decimal_places=0, max_digits=10000, null=True)),
                ('chance', models.DecimalField(decimal_places=0, max_digits=10000, null=True)),
                ('chance_string', models.TextField(null=True)),
                ('hunting_method', models.TextField()),
                ('binomial_distribution', models.FloatField(null=True)),
                ('shiny_charm', models.BooleanField(default=False)),
                ('caught', models.BooleanField(default=False)),
            ],
        ),
    ]
